import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Banner from "@/components/Banner";
import Card from "@/components/Card";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const handleOnBannerBtnClick = () => {
    console.log("hi banner btn");
  };
  return (
    <>
      <Head>
        <title>Coffee Store</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Banner
          buttonText="Visit Nearby Shops"
          handleOnClick={handleOnBannerBtnClick}
        />
        <div className={styles.heroImage}>
          <Image src="/static/hero-image.png" alt="" width={700} height={400} />
        </div>
        <div className={styles.cardLayout}>
          <Card
            href="/coffee-store/hello"
            title="Hello"
            imgURL="/static/hero-image.png"
            className={styles.card}
          />
          <Card
            href="/coffee-store/hello"
            title="Hello"
            imgURL="/static/hero-image.png"
            className={styles.card}
          />
          <Card
            href="/coffee-store/hello"
            title="Hello"
            imgURL="/static/hero-image.png"
            className={styles.card}
          />
        </div>
      </main>
    </>
  );
}
